name: GitHub Streak Maintainer  
on:  
  schedule:  
    - cron: '0 0 * * *'  # Runs daily at midnight  
  workflow_dispatch: # Allows manual trigger  

jobs:  
  commit:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v3  

      - name: Set up Python  
        uses: actions/setup-python@v3  
        with:  
          python-version: '3.x'  

      - name: Generate AI-powered script  
        run: python generate_code.py || echo "No script found, skipping"

      - name: Commit & push changes  
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  
        run: |  
          git config --global user.email "github-actions[bot]@users.noreply.github.com"  
          git config --global user.name "github-actions[bot]"  
          git add .  # Track all untracked files
          git commit -m "AI-generated commit to maintain streak 🚀" || echo "No changes to commit"  
          git push https://x-access-token:${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}@github.com/yash7tanwar/Auto.git HEAD:main
